# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -o bin/xeic-${{matrix.os}}-${{matrix.arch}} -v ./...

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
       name: xeic-bin-${{matrix.os}}-${{matrix.arch}}
       path: bin
